### PR TITLE
Fix version

### PR DESCRIPTION
**Pull request by AlekSi**

### CODE REVIEW

**Comment by AlekSi** [comment]
Will you merge that?

**Comment by aarzilli** [comment]
I can't merge on this repository, cc @derekparker

**Comment by alexejk** [comment]
While this isn't a major thing - it would be nice to have the version fixed :)

**Comment by aarzilli** [comment]
ping @derekparker

**Comment by AlekSi** [comment]
Thanks!

**Comment by derekparker** [comment]
Sorry for the delay!

**Pull request merged**
